spring:
  application:
    name: alibaba-sentinel-feign-client
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.11:8848
    # sentinel 控制台地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
# Feign开启sentinel服务
feign:
  sentinel:
    enabled: true
server:
  port: 8002


